[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[dev]
  command = "npm run dev"
  targetPort = 4321
  port = 8888
  publish = "dist"